CREATE TABLE IF NOT EXISTS `estados` (
  `EstID` int(11) NOT NULL AUTO_INCREMENT,
  `EstCodigo` varchar(3) COLLATE utf8_spanish2_ci NOT NULL,
  `EstPais` tinytext COLLATE utf8_spanish2_ci NOT NULL,
  `EstNombre` tinytext COLLATE utf8_spanish2_ci NOT NULL,
 PRIMARY KEY (`EstID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;

--
-- Dumping data for table `estados`
--

INSERT INTO `estados` (`EstID`, `EstCodigo`, `EstPais`, `EstNombre`) VALUES
(1, 'AGU', 'MEX', 'Aguascalientes'),
(2, 'BCN', 'MEX', 'Baja California'),
(3, 'BCS', 'MEX', 'Baja California Sur'),
(4, 'CAM', 'MEX', 'Campeche'),
(5, 'CHP', 'MEX', 'Chiapas'),
(6, 'CHH', 'MEX', 'Chihuahua'),
(7, 'COA', 'MEX', 'Coahuila'),
(8, 'COL', 'MEX', 'Colima'),
(9, 'DIF', 'MEX', 'Ciudad de México'),
(10, 'DUR', 'MEX', 'Durango'),
(11, 'GUA', 'MEX', 'Guanajuato'),
(12, 'GRO', 'MEX', 'Guerrero'),
(13, 'HID', 'MEX', 'Hidalgo'),
(14, 'JAL', 'MEX', 'Jalisco'),
(15, 'MEX', 'MEX', 'Estado de México'),
(16, 'MIC', 'MEX', 'Michoacán'),
(17, 'MOR', 'MEX', 'Morelos'),
(18, 'NAY', 'MEX', 'Nayarit'),
(19, 'NLE', 'MEX', 'Nuevo León'),
(20, 'OAX', 'MEX', 'Oaxaca'),
(21, 'PUE', 'MEX', 'Puebla'),
(22, 'QUE', 'MEX', 'Querétaro'),
(23, 'ROO', 'MEX', 'Quintana Roo'),
(24, 'SLP', 'MEX', 'San Luis Potosí'),
(25, 'SIN', 'MEX', 'Sinaloa'),
(26, 'SON', 'MEX', 'Sonora'),
(27, 'TAB', 'MEX', 'Tabasco'),
(28, 'TAM', 'MEX', 'Tamaulipas'),
(29, 'TLA', 'MEX', 'Tlaxcala'),
(30, 'VER', 'MEX', 'Veracruz'),
(31, 'YUC', 'MEX', 'Yucatán'),
(32, 'ZAC', 'MEX', 'Zacatecas'),
(33, 'AL', 'USA', 'Alabama'),
(34, 'AK', 'USA', 'Alaska'),
(35, 'AZ', 'USA', 'Arizona'),
(36, 'AR', 'USA', 'Arkansas'),
(37, 'CA', 'USA', 'California'),
(38, 'NC', 'USA', 'Carolina del Norte'),
(39, 'SC', 'USA', 'Carolina del Sur'),
(40, 'CO', 'USA', 'Colorado'),
(41, 'CT', 'USA', 'Connecticut'),
(42, 'ND', 'USA', 'Dakota del Norte'),
(43, 'SD', 'USA', 'Dakota del Sur'),
(44, 'DE', 'USA', 'Delaware'),
(45, 'FL', 'USA', 'Florida'),
(46, 'GA', 'USA', 'Georgia'),
(47, 'HI', 'USA', 'Hawái'),
(48, 'ID', 'USA', 'Idaho'),
(49, 'IL', 'USA', 'Illinois'),
(50, 'IN', 'USA', 'Indiana'),
(51, 'IA', 'USA', 'Iowa'),
(52, 'KS', 'USA', 'Kansas'),
(53, 'KY', 'USA', 'Kentucky'),
(54, 'LA', 'USA', 'Luisiana'),
(55, 'ME', 'USA', 'Maine'),
(56, 'MD', 'USA', 'Maryland'),
(57, 'MA', 'USA', 'Massachusetts'),
(58, 'MI', 'USA', 'Míchigan'),
(59, 'MN', 'USA', 'Minnesota'),
(60, 'MS', 'USA', 'Misisipi'),
(61, 'MO', 'USA', 'Misuri'),
(62, 'MT', 'USA', 'Montana'),
(63, 'NE', 'USA', 'Nebraska'),
(64, 'NV', 'USA', 'Nevada'),
(65, 'NJ', 'USA', 'Nueva Jersey'),
(66, 'NY', 'USA', 'Nueva York'),
(67, 'NH', 'USA', 'Nuevo Hampshire'),
(68, 'NM', 'USA', 'Nuevo México'),
(69, 'OH', 'USA', 'Ohio'),
(70, 'OK', 'USA', 'Oklahoma'),
(71, 'OR', 'USA', 'Oregón'),
(72, 'PA', 'USA', 'Pensilvania'),
(73, 'RI', 'USA', 'Rhode Island'),
(74, 'TN', 'USA', 'Tennessee'),
(75, 'TX', 'USA', 'Texas'),
(76, 'UT', 'USA', 'Utah'),
(77, 'VT', 'USA', 'Vermont'),
(78, 'VA', 'USA', 'Virginia'),
(79, 'WV', 'USA', 'Virginia Occidental'),
(80, 'WA', 'USA', 'Washington'),
(81, 'WI', 'USA', 'Wisconsin'),
(82, 'WY', 'USA', 'Wyoming'),
(83, 'ON', 'CAN', 'Ontario '),
(84, 'QC', 'CAN', ' Quebec '),
(85, 'NS', 'CAN', ' Nueva Escocia'),
(86, 'NB', 'CAN', 'Nuevo Brunswick '),
(87, 'MB', 'CAN', ' Manitoba'),
(88, 'BC', 'CAN', ' Columbia Británica'),
(89, 'PE', 'CAN', ' Isla del Príncipe Eduardo'),
(90, 'SK', 'CAN', ' Saskatchewan'),
(91, 'AB', 'CAN', ' Alberta'),
(92, 'NL', 'CAN', ' Terranova y Labrador'),
(93, 'NT', 'CAN', ' Territorios del Noroeste'),
(94, 'YT', 'CAN', ' Yukón'),
(95, 'UN', 'CAN', ' Nunavut');

