CREATE TABLE IF NOT EXISTS `paises` (
  `PaiID` int(11) NOT NULL AUTO_INCREMENT,
  `PaiCodigo` varchar(5) COLLATE utf8_spanish2_ci NOT NULL,
  `PaiNombre` tinytext COLLATE utf8_spanish2_ci NOT NULL,
  `PaiFormatoCodigo` tinytext COLLATE utf8_spanish2_ci NOT NULL,
  `PaiFormatoID` tinytext COLLATE utf8_spanish2_ci NOT NULL,
  `PaiFormatoValidacion` tinytext COLLATE utf8_spanish2_ci NOT NULL,
  `PaiAgrupacion` varchar(100) COLLATE utf8_spanish2_ci NOT NULL,
 PRIMARY KEY (`PaiID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;



INSERT INTO `paises` (`PaiID`, `PaiCodigo`, `PaiNombre`, `PaiFormatoCodigo`, `PaiFormatoID`, `PaiFormatoValidacion`, `PaiAgrupacion`) VALUES
(1, 'AFG', 'Afganistán', '', '', '', ''),
(2, 'ALA', 'Islas Åland', '', '', '', ''),
(3, 'ALB', 'Albania', '', '', '', ''),
(4, 'DEU', 'Alemania', '', '', '', 'Unión Europea'),
(5, 'AND', 'Andorra', '', '', '', ''),
(6, 'AGO', 'Angola', '', '', '', ''),
(7, 'AIA', 'Anguila', '', '', '', ''),
(8, 'ATA', 'Antártida', '', '', '', ''),
(9, 'ATG', 'Antigua y Barbuda', '', '', '', ''),
(10, 'SAU', 'Arabia Saudita', '', '', '', ''),
(11, 'DZA', 'Argelia', '', '', '', ''),
(12, 'ARG', 'Argentina', '', '', '', ''),
(13, 'ARM', 'Armenia', '', '', '', ''),
(14, 'ABW', 'Aruba', '', '', '', ''),
(15, 'AUS', 'Australia', '', '', '', ''),
(16, 'AUT', 'Austria', '', '', '', 'Unión Europea'),
(17, 'AZE', 'Azerbaiyán', '', '', '', ''),
(18, 'BHS', 'Bahamas (las)', '', '', '', ''),
(19, 'BGD', 'Bangladés', '', '', '', ''),
(20, 'BRB', 'Barbados', '', '', '', ''),
(21, 'BHR', 'Baréin', '', '', '', ''),
(22, 'BEL', 'Bélgica', '', '', '', 'Unión Europea'),
(23, 'BLZ', 'Belice', '', '', '', ''),
(24, 'BEN', 'Benín', '', '', '', ''),
(25, 'BMU', 'Bermudas', '', '', '', ''),
(26, 'BLR', 'Bielorrusia', '', '', '', ''),
(27, 'MMR', 'Myanmar', '', '', '', ''),
(28, 'BOL', 'Bolivia, Estado Plurinacional de', '', '', '', ''),
(29, 'BIH', 'Bosnia y Herzegovina', '', '', '', ''),
(30, 'BWA', 'Botsuana', '', '', '', ''),
(31, 'BRA', 'Brasil', '', '', '', ''),
(32, 'BRN', 'Brunéi Darussalam', '', '', '', ''),
(33, 'BGR', 'Bulgaria', '', '', '', 'Unión Europea'),
(34, 'BFA', 'Burkina Faso', '', '', '', ''),
(35, 'BDI', 'Burundi', '', '', '', ''),
(36, 'BTN', 'Bután', '', '', '', ''),
(37, 'CPV', 'Cabo Verde', '', '', '', ''),
(38, 'KHM', 'Camboya', '', '', '', ''),
(39, 'CMR', 'Camerún', '', '', '', ''),
(40, 'CAN', 'Canadá', '[A-Z][0-9][A-Z] [0-9][A-Z][0-9]', '[0-9]{9}', '', 'TLCAN'),
(41, 'QAT', 'Catar', '', '', '', ''),
(42, 'BES', 'Bonaire, San Eustaquio y Saba', '', '', '', ''),
(43, 'TCD', 'Chad', '', '', '', ''),
(44, 'CHL', 'Chile', '', '', '', ''),
(45, 'CHN', 'China', '', '', '', ''),
(46, 'CYP', 'Chipre', '', '', '', 'Unión Europea'),
(47, 'COL', 'Colombia', '', '', '', ''),
(48, 'COM', 'Comoras', '', '', '', ''),
(49, 'PRK', 'Corea (la República Democrática Popular de)', '', '', '', ''),
(50, 'KOR', 'Corea (la República de)', '', '', '', ''),
(51, 'CIV', 'Côte d''Ivoire', '', '', '', ''),
(52, 'CRI', 'Costa Rica', '', '', '', ''),
(53, 'HRV', 'Croacia', '', '', '', 'Unión Europea'),
(54, 'CUB', 'Cuba', '', '', '', ''),
(55, 'CUW', 'Curaçao', '', '', '', ''),
(56, 'DNK', 'Dinamarca', '', '', '', 'Unión Europea'),
(57, 'DMA', 'Dominica', '', '', '', ''),
(58, 'ECU', 'Ecuador', '', '', '', ''),
(59, 'EGY', 'Egipto', '', '', '', ''),
(60, 'SLV', 'El Salvador', '', '', '', ''),
(61, 'ARE', 'Emiratos Árabes Unidos (Los)', '', '', '', ''),
(62, 'ERI', 'Eritrea', '', '', '', ''),
(63, 'SVK', 'Eslovaquia', '', '', '', 'Unión Europea'),
(64, 'SVN', 'Eslovenia', '', '', '', 'Unión Europea'),
(65, 'ESP', 'España', '', '', '', 'Unión Europea'),
(66, 'USA', 'Estados Unidos (los)', '[0-9]{5}(-[0-9]{4})?', '[0-9]{9}', '', 'TLCAN'),
(67, 'EST', 'Estonia', '', '', '', 'Unión Europea'),
(68, 'ETH', 'Etiopía', '', '', '', ''),
(69, 'PHL', 'Filipinas (las)', '', '', '', ''),
(70, 'FIN', 'Finlandia', '', '', '', 'Unión Europea'),
(71, 'FJI', 'Fiyi', '', '', '', ''),
(72, 'FRA', 'Francia', '', '', '', 'Unión Europea'),
(73, 'GAB', 'Gabón', '', '', '', ''),
(74, 'GMB', 'Gambia (La)', '', '', '', ''),
(75, 'GEO', 'Georgia', '', '', '', ''),
(76, 'GHA', 'Ghana', '', '', '', ''),
(77, 'GIB', 'Gibraltar', '', '', '', ''),
(78, 'GRD', 'Granada', '', '', '', ''),
(79, 'GRC', 'Grecia', '', '', '', 'Unión Europea'),
(80, 'GRL', 'Groenlandia', '', '', '', ''),
(81, 'GLP', 'Guadalupe', '', '', '', ''),
(82, 'GUM', 'Guam', '', '', '', ''),
(83, 'GTM', 'Guatemala', '', '', '', ''),
(84, 'GUF', 'Guayana Francesa', '', '', '', ''),
(85, 'GGY', 'Guernsey', '', '', '', ''),
(86, 'GIN', 'Guinea', '', '', '', ''),
(87, 'GNB', 'Guinea-Bisáu', '', '', '', ''),
(88, 'GNQ', 'Guinea Ecuatorial', '', '', '', ''),
(89, 'GUY', 'Guyana', '', '', '', ''),
(90, 'HTI', 'Haití', '', '', '', ''),
(91, 'HND', 'Honduras', '', '', '', ''),
(92, 'HKG', 'Hong Kong', '', '', '', ''),
(93, 'HUN', 'Hungría', '', '', '', 'Unión Europea'),
(94, 'IND', 'India', '', '', '', ''),
(95, 'IDN', 'Indonesia', '', '', '', ''),
(96, 'IRQ', 'Irak', '', '', '', ''),
(97, 'IRN', 'Irán (la República Islámica de)', '', '', '', ''),
(98, 'IRL', 'Irlanda', '', '', '', 'Unión Europea'),
(99, 'BVT', 'Isla Bouvet', '', '', '', ''),
(100, 'IMN', 'Isla de Man', '', '', '', ''),
(101, 'CXR', 'Isla de Navidad', '', '', '', ''),
(102, 'NFK', 'Isla Norfolk', '', '', '', ''),
(103, 'ISL', 'Islandia', '', '', '', ''),
(104, 'CYM', 'Islas Caimán (las)', '', '', '', ''),
(105, 'CCK', 'Islas Cocos (Keeling)', '', '', '', ''),
(106, 'COK', 'Islas Cook (las)', '', '', '', ''),
(107, 'FRO', 'Islas Feroe (las)', '', '', '', ''),
(108, 'SGS', 'Georgia del sur y las islas sandwich del sur', '', '', '', ''),
(109, 'HMD', 'Isla Heard e Islas McDonald', '', '', '', ''),
(110, 'FLK', 'Islas Malvinas [Falkland] (las)', '', '', '', ''),
(111, 'MNP', 'Islas Marianas del Norte (las)', '', '', '', ''),
(112, 'MHL', 'Islas Marshall (las)', '', '', '', ''),
(113, 'PCN', 'Pitcairn', '', '', '', ''),
(114, 'SLB', 'Islas Salomón (las)', '', '', '', ''),
(115, 'TCA', 'Islas Turcas y Caicos (las)', '', '', '', ''),
(116, 'UMI', 'Islas de Ultramar Menores de Estados Unidos (las)', '', '', '', ''),
(117, 'VGB', 'Islas Vírgenes (Británicas)', '', '', '', ''),
(118, 'VIR', 'Islas Vírgenes (EE.UU.)', '', '', '', ''),
(119, 'ISR', 'Israel', '', '', '', ''),
(120, 'ITA', 'Italia', '', '', '', 'Unión Europea'),
(121, 'JAM', 'Jamaica', '', '', '', ''),
(122, 'JPN', 'Japón', '', '', '', ''),
(123, 'JEY', 'Jersey', '', '', '', ''),
(124, 'JOR', 'Jordania', '', '', '', ''),
(125, 'KAZ', 'Kazajistán', '', '', '', ''),
(126, 'KEN', 'Kenia', '', '', '', ''),
(127, 'KGZ', 'Kirguistán', '', '', '', ''),
(128, 'KIR', 'Kiribati', '', '', '', ''),
(129, 'KWT', 'Kuwait', '', '', '', ''),
(130, 'LAO', 'Lao, (la) República Democrática Popular', '', '', '', ''),
(131, 'LSO', 'Lesoto', '', '', '', ''),
(132, 'LVA', 'Letonia', '', '', '', 'Unión Europea'),
(133, 'LBN', 'Líbano', '', '', '', ''),
(134, 'LBR', 'Liberia', '', '', '', ''),
(135, 'LBY', 'Libia', '', '', '', ''),
(136, 'LIE', 'Liechtenstein', '', '', '', ''),
(137, 'LTU', 'Lituania', '', '', '', 'Unión Europea'),
(138, 'LUX', 'Luxemburgo', '', '', '', 'Unión Europea'),
(139, 'MAC', 'Macao', '', '', '', ''),
(140, 'MDG', 'Madagascar', '', '', '', ''),
(141, 'MYS', 'Malasia', '', '', '', ''),
(142, 'MWI', 'Malaui', '', '', '', ''),
(143, 'MDV', 'Maldivas', '', '', '', ''),
(144, 'MLI', 'Malí', '', '', '', ''),
(145, 'MLT', 'Malta', '', '', '', 'Unión Europea'),
(146, 'MAR', 'Marruecos', '', '', '', ''),
(147, 'MTQ', 'Martinica', '', '', '', ''),
(148, 'MUS', 'Mauricio', '', '', '', ''),
(149, 'MRT', 'Mauritania', '', '', '', ''),
(150, 'MYT', 'Mayotte', '', '', '', ''),
(151, 'MEX', 'México', '[0-9]{5}', '[A-Z&Ñ]{3,4}[0-9]{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])[A-Z0-9]{2}[0\n-9A]', 'Lista del SAT', 'TLCAN'),
(152, 'FSM', 'Micronesia (los Estados Federados de)', '', '', '', ''),
(153, 'MDA', 'Moldavia (la República de)', '', '', '', ''),
(154, 'MCO', 'Mónaco', '', '', '', ''),
(155, 'MNG', 'Mongolia', '', '', '', ''),
(156, 'MNE', 'Montenegro', '', '', '', ''),
(157, 'MSR', 'Montserrat', '', '', '', ''),
(158, 'MOZ', 'Mozambique', '', '', '', ''),
(159, 'NAM', 'Namibia', '', '', '', ''),
(160, 'NRU', 'Nauru', '', '', '', ''),
(161, 'NPL', 'Nepal', '', '', '', ''),
(162, 'NIC', 'Nicaragua', '', '', '', ''),
(163, 'NER', 'Níger (el)', '', '', '', ''),
(164, 'NGA', 'Nigeria', '', '', '', ''),
(165, 'NIU', 'Niue', '', '', '', ''),
(166, 'NOR', 'Noruega', '', '', '', ''),
(167, 'NCL', 'Nueva Caledonia', '', '', '', ''),
(168, 'NZL', 'Nueva Zelanda', '', '', '', ''),
(169, 'OMN', 'Omán', '', '', '', ''),
(170, 'NLD', 'Países Bajos (los)', '', '', '', 'Unión Europea'),
(171, 'PAK', 'Pakistán', '', '', '', ''),
(172, 'PLW', 'Palaos', '', '', '', ''),
(173, 'PSE', 'Palestina, Estado de', '', '', '', ''),
(174, 'PAN', 'Panamá', '', '', '', ''),
(175, 'PNG', 'Papúa Nueva Guinea', '', '', '', ''),
(176, 'PRY', 'Paraguay', '', '', '', ''),
(177, 'PER', 'Perú', '', '', '', ''),
(178, 'PYF', 'Polinesia Francesa', '', '', '', ''),
(179, 'POL', 'Polonia', '', '', '', 'Unión Europea'),
(180, 'PRT', 'Portugal', '', '', '', 'Unión Europea'),
(181, 'PRI', 'Puerto Rico', '', '', '', ''),
(182, 'GBR', 'Reino Unido (el)', '', '', '', 'Unión Europea'),
(183, 'CAF', 'República Centroafricana (la)', '', '', '', ''),
(184, 'CZE', 'República Checa (la)', '', '', '', 'Unión Europea'),
(185, 'MKD', 'Macedonia (la antigua República Yugoslava de)', '', '', '', ''),
(186, 'COG', 'Congo', '', '', '', ''),
(187, 'COD', 'Congo (la República Democrática del)', '', '', '', ''),
(188, 'DOM', 'República Dominicana (la)', '', '', '', ''),
(189, 'REU', 'Reunión', '', '', '', ''),
(190, 'RWA', 'Ruanda', '', '', '', ''),
(191, 'ROU', 'Rumania', '', '', '', 'Unión Europea'),
(192, 'RUS', 'Rusia, (la) Federación de', '', '', '', ''),
(193, 'ESH', 'Sahara Occidental', '', '', '', ''),
(194, 'WSM', 'Samoa', '', '', '', ''),
(195, 'ASM', 'Samoa Americana', '', '', '', ''),
(196, 'BLM', 'San Bartolomé', '', '', '', ''),
(197, 'KNA', 'San Cristóbal y Nieves', '', '', '', ''),
(198, 'SMR', 'San Marino', '', '', '', ''),
(199, 'MAF', 'San Martín (parte francesa)', '', '', '', ''),
(200, 'SPM', 'San Pedro y Miquelón', '', '', '', ''),
(201, 'VCT', 'San Vicente y las Granadinas', '', '', '', ''),
(202, 'SHN', 'Santa Helena, Ascensión y Tristán de Acuña', '', '', '', ''),
(203, 'LCA', 'Santa Lucía', '', '', '', ''),
(204, 'STP', 'Santo Tomé y Príncipe', '', '', '', ''),
(205, 'SEN', 'Senegal', '', '', '', ''),
(206, 'SRB', 'Serbia', '', '', '', ''),
(207, 'SYC', 'Seychelles', '', '', '', ''),
(208, 'SLE', 'Sierra leona', '', '', '', ''),
(209, 'SGP', 'Singapur', '', '', '', ''),
(210, 'SXM', 'Sint Maarten (parte holandesa)', '', '', '', ''),
(211, 'SYR', 'Siria, (la) República Árabe', '', '', '', ''),
(212, 'SOM', 'Somalia', '', '', '', ''),
(213, 'LKA', 'Sri Lanka', '', '', '', ''),
(214, 'SWZ', 'Suazilandia', '', '', '', ''),
(215, 'ZAF', 'Sudáfrica', '', '', '', ''),
(216, 'SDN', 'Sudán (el)', '', '', '', ''),
(217, 'SSD', 'Sudán del Sur', '', '', '', ''),
(218, 'SWE', 'Suecia', '', '', '', 'Unión Europea'),
(219, 'CHE', 'Suiza', '', '', '', ''),
(220, 'SUR', 'Surinam', '', '', '', ''),
(221, 'SJM', 'Svalbard y Jan Mayen', '', '', '', ''),
(222, 'THA', 'Tailandia', '', '', '', ''),
(223, 'TWN', 'Taiwán (Provincia de China)', '', '', '', ''),
(224, 'TZA', 'Tanzania, República Unida de', '', '', '', ''),
(225, 'TJK', 'Tayikistán', '', '', '', ''),
(226, 'IOT', 'Territorio Británico del Océano Índico (el)', '', '', '', ''),
(227, 'ATF', 'Territorios Australes Franceses (los)', '', '', '', ''),
(228, 'TLS', 'Timor-Leste', '', '', '', ''),
(229, 'TGO', 'Togo', '', '', '', ''),
(230, 'TKL', 'Tokelau', '', '', '', ''),
(231, 'TON', 'Tonga', '', '', '', ''),
(232, 'TTO', 'Trinidad y Tobago', '', '', '', ''),
(233, 'TUN', 'Túnez', '', '', '', ''),
(234, 'TKM', 'Turkmenistán', '', '', '', ''),
(235, 'TUR', 'Turquía', '', '', '', ''),
(236, 'TUV', 'Tuvalu', '', '', '', ''),
(237, 'UKR', 'Ucrania', '', '', '', ''),
(238, 'UGA', 'Uganda', '', '', '', ''),
(239, 'URY', 'Uruguay', '', '', '', ''),
(240, 'UZB', 'Uzbekistán', '', '', '', ''),
(241, 'VUT', 'Vanuatu', '', '', '', ''),
(242, 'VAT', 'Santa Sede[Estado de la Ciudad del Vaticano] (la)', '', '', '', ''),
(243, 'VEN', 'Venezuela, República Bolivariana de', '', '', '', ''),
(244, 'VNM', 'Viet Nam', '', '', '', ''),
(245, 'WLF', 'Wallis y Futuna', '', '', '', ''),
(246, 'YEM', 'Yemen', '', '', '', ''),
(247, 'DJI', 'Yibuti', '', '', '', ''),
(248, 'ZMB', 'Zambia', '', '', '', ''),
(249, 'ZWE', 'Zimbabue', '', '', '', ''),
(250, 'ZZZ', 'Países no declarados', '', '', '', '');
